
#SPLIT_KEYBOARD = yes
#AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
#OLED_ENABLE = yes
#RAW_ENABLE = no
#OS_DETECTION_ENABLE = no
KEY_OVERRIDE_ENABLE = no
#RGB_MATRIX = n
MOUSEKEY_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGB_MATRIX_USER = no
SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_TRANSPORT_MIRROR = yes
CONSOLE_ENABLE = yes
RAW_ENABLE = yes
UNICODEMAP_ENABLE = yes
